### ISSUE TITLE
Debugging Practice

### ISSUE THREAD

**Issue by Hamzaoutdoors** [nelsinofrancisco/microverse_portifolio#13]
## Bug Found
https://github.com/nelsinofrancisco/microverse_portifolio/blob/0cc5ce4d36a67ba7ef4a8af0a42c6b7e866adf87/generate_works_section.js#L422
in this line you wrote "cardWorkContaIner", it should be "cardWorkContainer" 
fix just this error and your code will work great

**Comment by nelsinofrancisco** [comment]
You got it right Hamza, congratulations!
