### ISSUE TITLE
MODULE 1: FIRST MORNING SESSION ISSUE

### ISSUE THREAD

**Issue by Hamzaoutdoors** [nelsinofrancisco/microverse_portifolio#4]
# FIRST MORNING SESSION ISSUE
Good job so far! 👏🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

##  Please work on these feedbacks:

- Can you please add active in your form to collect data by using the Formspree service [Formspree](https://formspree.io/html)

_Good luck and keep coding ❤️_

**Comment by nelsinofrancisco** [comment]
### Hello Hamza!

I've changed the form element, thx for the feedback
